CREATE TABLE client (
   id BIGSERIAL PRIMARY KEY,
   name VARCHAR(60) NOT NULL
);
CREATE TABLE contact (
   id BIGSERIAL PRIMARY KEY,
   client_id BIGINT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
   type VARCHAR(50) NOT NULL,
   value VARCHAR(50) NOT NULL
);